logging-to-file = true        # enables logging of every patch process to a seperate file
enable-magisk-update = true   # set this to false if you do not want to receive updates for the module in magisk app

# add 'enabled = false' for not patching a specific app or remove it from the config
# see https://github.com/j-hc/revanced-magisk-module/blob/main/CONFIG.md for more detailed explanations

# you can use rvmm-config-gen to generate a config

[Music]
app-name = "YouTube-Music"
patches-source = "inotia00/revanced-patches"
integrations-source = "inotia00/revanced-integrations"
cli-source = "inotia00/revanced-cli"
rv-brand = "ReVanced Extended"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube-music/"
apkmirror-arch = "arm64-v8a"

[YouTube]
patches-source = "inotia00/revanced-patches"
integrations-source = "inotia00/revanced-integrations"
cli-source = "inotia00/revanced-cli"
rv-brand = "ReVanced Extended"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube/"
apkmirror-arch = "arm64-v8a"

[Twitter]
cli-source = "ReVanced/revanced-cli"
archive-dlurl = "https://downloadr2.apkmirror.com/wp-content/uploads/2023/12/62/656f6a69e06b6/com.twitter.android_10.19.0-release.0-310190000_minAPI23(arm64-v8a,armeabi-v7a,x86,x86_64)(nodpi)_apkmirror.com.apk?verify=1702153574-x8bN4pWu_C7NUF32V_AteRwJduu_LfrGz8it4keHR_4"

[TikTok]
cli-source = "ReVanced/revanced-cli"
apkmirror-dlurl = "https://www.apkmirror.com/apk/tiktok-pte-ltd/tik-tok-including-musical-ly/"
version = "latest"

[Facebook]
cli-source = "ReVanced/revanced-cli"
apkmirror-dlurl ="https://downloadr2.apkmirror.com/wp-content/uploads/2023/12/23/6570f25f9c194/com.facebook.katana_443.0.0.23.229-447626366_minAPI30(arm64-v8a)(nodpi)_apkmirror.com.apk?verify=1702153480-ouclceZBHLmr2Eq8UVsbGyA5CjweC_O7FQk4x7BA7hs"

[Messenger]
cli-source = "ReVanced/revanced-cli"
apkmirror-dlurl ="https://www.apkmirror.com/apk/facebook-2/messenger/"
apkmirror-arch = "arm64-v8a"

[Spotify]
cli-source = "ReVanced/revanced-cli"
uptodown-dlurl = "https://spotify.en.uptodown.com/android"
apkmirror-arch = "arm64-v8a"

[Instagram]
cli-source = "ReVanced/revanced-cli"
apkmirror-dlurl = "https://www.apkmirror.com/apk/instagram/instagram-instagram/"
apkmirror-arch = "arm64-v8a"

[pixiv]
cli-source = "ReVanced/revanced-cli"
apkmirror-dlurl = "https://www.apkmirror.com/apk/pixiv-inc/pixiv/"
apkmirror-arch = "arm64-v8a"
