enable-magisk-update = false   # set this to false if you do not want to receive updates for the module in magisk app
patches-source = "inotia00/revanced-patches"
integrations-source = "inotia00/revanced-integrations"
cli-source = "inotia00/revanced-cli"
rv-brand = "ReVanced eXtended"

# add 'enabled = false' for not patching a specific app or remove it from the config
# see https://github.com/j-hc/revanced-magisk-module/blob/main/CONFIG.md for more detailed explanations

# you can use rvmm-config-gen to generate a config

[YouTube]                                                                                                                                                                           
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube/"
module-prop-name = "yt-rvx"
arch = "arm64-v8a"

[Music]
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube-music/"
module-prop-name = "ytm-rvx"
arch = "arm64-v8a"

[Twitter]
cli-source = "ReVanced/revanced-cli"
apkmirror-dlurl = "https://www.apkmirror.com/?post_type=app_release&searchtype=apk&s=twitter"
#uptodown-dlurl = "https://twitter.th.uptodown.com/android"
#included-patches = "'Hide ads'"

[TikTok]
cli-source = "ReVanced/revanced-cli"
apkmirror-dlurl = "https://www.apkmirror.com/apk/tiktok-pte-ltd/tik-tok/"

[Facebook]
cli-source = "ReVanced/revanced-cli"
uptodown-dlurl = "https://facebook.th.uptodown.com/android"
apkmirror-arch = "arm64-v8a"

[Messenger]
cli-source = "ReVanced/revanced-cli"
apkmirror-dlurl ="https://www.apkmirror.com/apk/facebook-2/messenger/"
apkmirror-arch = "arm64-v8a"
#uptodown-dlurl = "https://facebook-messenger.th.uptodown.com/android"

[Spotify] #No Remove Ads
cli-source = "ReVanced/revanced-cli"
#apkmonk-dlurl = "https://www.apkmonk.com/app/com.spotify.music/"
uptodown-dlurl = "https://spotify.th.uptodown.com/android"

[Instagram]
cli-source = "ReVanced/revanced-cli"
apkmirror-dlurl = "https://www.apkmirror.com/apk/instagram/instagram-instagram/"
apkmirror-arch = "arm64-v8a"
#uptodown-dlurl = "https://instagram.th.uptodown.com/android"

[pixiv]
cli-source = "ReVanced/revanced-cli"
apkmirror-dlurl = "https://www.apkmirror.com/apk/pixiv-inc/pixiv/"
